### ISSUE TITLE
[News] View other news from the news content page

### ISSUE THREAD

**Issue by OlenaOsadchaBA** [ita-social-projects/TeachUA#1408]
**As a user I want to see other news from the news page content so that I will be able to get familiar with other news** 

**Description**
Provide users to see other news without backing to the 'News' page

**Mockup**
https://www.figma.com/file/YSXBEZfBiDNr3dgOpMhTtH/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E?node-id=233%3A4051
![image](https://user-images.githubusercontent.com/103151401/168640906-112fffc7-ffee-46f0-b41f-751fa34bb247.png)

**Acceptance Criteria**

1. The system should display existing news in the DB.
2. The system should display news by descending values in the 'Дата новини' field.
3. If news has the same values in the 'Дата новини' field, the system should display the last added news the first in the list within the same date.
4. The page should support the carousel for news navigation.
5. The system should not display the current news in the list. 
6. The system should display each news in a single block, which should be clickable.
7. The system should display in the block:
- the picture associated with the news (the picture from the 'Фото банер' field).
-the text from the 'Заголовок' field.
-the value from the 'Дата новини' field.
8. The picture in the block should be compressed and displayed the whole picture.
9. When the user clicks on the block OR on the 'Переглянути' button, the system should open the content page for the selected news. User story #1407 

**Epic link**
E.g.: Epic #1379

**Comment by KostiantynStarynets** [comment]
https://speak-ukrainian.org.ua/news
According to the criteria, everything works correctly. But point "8. The picture in the block must be compressed and display the picture in its entirety." - it is not possible to check, because there is no news with pictures, but there is only a video - which works correctly. The "Переглянути" button is specified in the criteria, it is now called "Детальніше"
![Знімок екрана 2022-12-06 234444](https://user-images.githubusercontent.com/117648097/206033053-d720df64-3c91-4bb3-bcea-411c94eda0cb.jpg)
